<?php
defined('BASEPATH') OR exit('No direct script access allowed');


$config['base_url']       = 'https://www.airtrippy.vn';
$config['base_url_front'] = 'https://www.airtrippy.vn';
$config['base_tlp_front'] = 'https://www.airtrippy.vn/assets/front/panpic';

$config['base_url_admin'] = 'https://www.airtrippy.vn/admin';
$config['base_tlp_admin'] = 'https://www.airtrippy.vn/assets/admin/darkgreen';

$config['base_url_user'] = 'https://www.airtrippy.vn/user';
$config['base_tlp_user'] = 'https://www.airtrippy.vn/assets/user/panpic';
 

$config['path_upload']   = FCPATH."/files/uploads/"; 
$config['path_logo']     = FCPATH."/files/uploads/logo";
$config['path_thumb']    = FCPATH."/files/uploads/thumb";
$config['path_category'] = FCPATH."/files/uploads/category";
$config['path_download'] = FCPATH."/files/uploads/download";
$config['path_attach']   = FCPATH."/files/uploads/attach";

$config['dir_logo']      = '/files/uploads/logo/'; 
$config['dir_category']  = '/files/uploads/category/'; 
$config['dir_thumb']     = '/files/uploads/thumb/';
$config['dir_download']  = '/files/uploads/download/'; 
$config['dir_attach']    = '/files/uploads/attach/';

$config['agency_sku']    = 'AG';
$config['tour_sku']      = 'TO';
$config['blog_sku']      = 'BO';

// Cookie
$config['domain_cookie'] = 'airtrippy.vn';
$config['prefix_cookie'] = 'airtrippy_';

$config['user_cookie']      = 'user_set';
$config['user_path']        = '/'; 
$config['user_expire']      = time()+86500;

$config['session_enduser']  = 'userData';
$config['session_agency']   = 'agency';


/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

$config['language']	= 'english';

$config['charset'] = 'UTF-8';

$config['enable_hooks'] = FALSE;

$config['subclass_prefix'] = 'MY_';

$config['composer_autoload'] = TRUE;

$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


$config['allow_get_array'] = TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';


$config['log_threshold'] = 0;

$config['log_path'] = '';

$config['log_file_extension'] = '';

$config['log_file_permissions'] = 0644;

$config['log_date_format'] = 'Y-m-d H:i:s';

$config['error_views_path'] = '';

$config['cache_path'] = '';

$config['cache_query_string'] = FALSE;

$config['encryption_key'] = 'max';


$config['sess_cookie_name']	= 'ci_session';
$config['sess_expiration']	= 7200;
$config['sess_expire_on_close']	= TRUE;
$config['sess_encrypt_cookie']	= FALSE;
$config['sess_use_database']	= TRUE;
$config['sess_table_name']	= 'ci_sessions';
$config['sess_match_ip']	= FALSE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;


$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;

$config['standardize_newlines'] = FALSE;

$config['global_xss_filtering'] = FALSE;

$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

$config['compress_output'] = FALSE;

$config['time_reference'] = 'local';

$config['rewrite_short_tags'] = TRUE;

$config['proxy_ips'] = '';

// $config['smarty.template_error_reporting'] = E_ALL ^ E_NOTICE;
